import { useProfile } from "./profile";
import { LABELS, MESSAGES, VERDICT_TEXTS, type Locale } from "./shared";

// Teksty interfejsu aplikacji. Komunikaty oceny i etykiety danych są we wspólnym
// module (src/lib/i18n.ts, src/lib/labels.ts), żeby web i aplikacja mówiły tak samo.

const pl = {
  // zakładki i nagłówki
  tabSearch: "Szukaj",
  tabMap: "Mapa",
  tabNeeds: "Potrzeby",
  tabInfo: "Info",
  needsTitle: "Twoje potrzeby",
  infoTitle: "Źródła i metoda",
  reportTitle: "Zgłoś poprawkę",
  back: "Wróć",
  // ekran główny
  brand: "Bez barier",
  cityLabel: (c: string) => `Miasto: ${c}. Zmień miasto`,
  pickCity: "Wybierz miasto",
  heroTitle: "Dokąd się wybierasz?",
  heroBody: "Sprawdzimy bariery i udogodnienia pod Twoje potrzeby — ze źródłem i datą.",
  howYouMove: "Czym się poruszasz?",
  searchLabel: "Nazwa miejsca lub adres",
  searchPlaceholder: "Muzeum, kawiarnia, ulica…",
  clear: "Wyczyść",
  search: "Szukaj",
  all: "Wszystkie",
  nearMe: "Najbliżej mnie",
  onlyMatching: "Tylko spełniające wymagania",
  loading: "Wczytywanie…",
  places: (n: number) => `${n} ${n === 1 ? "miejsce" : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) ? "miejsca" : "miejsc"}`,
  nearest: " · od najbliższych",
  offlineTitle: "Jesteś offline — zapisana kopia",
  offlineBody: (d: string) => `Wyniki z ${d}. Mogą być nieaktualne.`,
  sourcesDownTitle: "Część źródeł jest niedostępna",
  sourcesDownBody: (names: string) => `Brak danych z: ${names}. Brak informacji nie oznacza braku barier.`,
  noServer: "Brak połączenia z serwerem i brak zapisanej kopii. Spróbuj ponownie, gdy będziesz online.",
  noLocation: "Bez zgody na lokalizację pokażemy wyniki według nazwy. Możesz wpisać adres.",
  openDetails: "Otwiera szczegóły i źródła",
  generalOnlyNote: "Na podstawie ogólnej oceny, bez szczegółowych pomiarów.",
  tagSample: "Dane przykładowe",
  tagUnverified: "Niezweryfikowane",
  tagStale: "Mogą być nieaktualne",
  tagStaleOne: "Może być nieaktualne",
  tagConfirmed: "Potwierdzone przez kilka źródeł",
  tagConflict: "Sprzeczne dane",
  // mapa
  mapLabel: "Mapa miejsc. Te same informacje są dostępne w liście.",
  mapHint: (n: number) => `${n} miejsc z wyszukiwania. Dotknij znacznika, aby zobaczyć szczegóły.`,
  mapDetails: "Szczegóły i źródła",
  mapAttribution: "Dane miejsc: © współtwórcy OpenStreetMap",
  // karta miejsca
  loadFailed: "Nie udało się wczytać miejsca. Sprawdź połączenie.",
  verdictA11y: (title: string, body: string) => `Ocena: ${title}. ${body}`,
  offlineCopyTitle: "Jesteś offline — zapisana kopia",
  offlineCopyBody: (d: string) => `Stan z ${d}.`,
  sampleTitle: "Dane przykładowe",
  sampleBody: "Wpis przygotowany na potrzeby demonstracji — nie opisuje rzeczywistego obiektu.",
  generalTitle: "Ocena ogólna",
  generalBody: "Źródło podaje „dostępne”, ale bez szczegółowych pomiarów wejścia i drzwi.",
  unverifiedTitle: "Niezweryfikowane informacje",
  unverifiedBody: "Część informacji pochodzi tylko ze zgłoszeń użytkowników.",
  staleTitle: "Mogą być nieaktualne",
  staleBody: "Część informacji ma ponad 2 lata.",
  yourRequirements: "Twoje wymagania",
  changeRequirements: "Zmień swoje wymagania",
  barriersTitle: "Bariery i udogodnienia",
  barriersHint: "Dotknij, aby zobaczyć źródło, datę i wiarygodność każdej informacji.",
  noInfo: "brak informacji",
  noInfoA11y: (label: string) => `${label}: brak informacji`,
  dateUnknown: "data nieznana",
  seeRecord: "Zobacz rekord w źródle →",
  stillTrue: "Byłeś na miejscu? Czy to nadal aktualne?",
  whichTrue: "Byłeś na miejscu? Która wersja jest prawdziwa?",
  yesCurrent: "Tak, aktualne",
  noReport: "Nie, zgłoś zmianę",
  thanksConfirm: "Dziękujemy — potwierdzenie zapisane.",
  confirmFailed: "Nie udało się zapisać. Spróbuj ponownie.",
  confirmNote: "Potwierdzenie aktualności na miejscu",
  transitTitle: "Dojazd komunikacją",
  onMap: "Na mapie",
  ownerTitle: "Prowadzisz to miejsce?",
  ownerBody: "Opisz dostępność obiektu — deklaracja pojawi się tu z datą, a kartę możesz osadzić na swojej stronie.",
  ownerButton: "Wypełnij deklarację dostępności",
  osmTitle: "Aktualność danych OSM",
  osmBody: "Dane OpenStreetMap są importowane codziennie. Możesz sprawdzić ten obiekt teraz.",
  osmChecking: "Sprawdzam…",
  osmCheck: "Sprawdź teraz w OpenStreetMap",
  osmChanged: "W OSM są zmiany od ostatniego importu",
  osmSame: "Dane w OSM nie zmieniły się od importu",
  osmLastEdit: (d: string) => `Ostatnia edycja obiektu w OSM: ${d}.`,
  osmFailTitle: "Nie udało się połączyć z OpenStreetMap",
  osmFailBody: (d: string) => `Pokazujemy kopię z ${d}. Nie traktuj jej jako potwierdzenia bieżącego stanu.`,
  lastImport: "ostatniego importu",
  navigate: "Prowadź",
  reportChange: "Zgłoś zmianę",
  // przystanki
  noStops: "Brak przystanków w promieniu 600 m w danych ZTP.",
  stopsHint: "Najbliższe przystanki i to, jak się z nich wsiada. Odległość w linii prostej.",
  mode: { bus: "autobus", tram: "tramwaj", bus_tram: "autobus i tramwaj" },
  approx: (m: number) => `ok. ${m} m`,
  rest: "Odpoczynek",
  shelter: (n: number) => `wiata (${n})`,
  benches: (n: number) => `ławki (${n})`,
  noRest: "brak wiaty i ławek",
  // potrzeby
  needsIntro: "Wybierz, czym się poruszasz, albo ustaw własne wymagania. Nie pytamy o niepełnosprawność — wystarczą Twoje potrzeby.",
  detailedRequirements: "Szczegółowe wymagania",
  maxStep: "Najwyższy próg, który pokonam (cm)",
  maxStepHint: "Na przykład 2 dla wózka ręcznego",
  minDoor: "Potrzebna szerokość przejścia (cm)",
  minDoorHint: "Na przykład 80",
  needToilet: "Potrzebuję toalety dostępnej dla wózka",
  needChanging: "Potrzebuję przewijaka",
  avoidCobbles: "Unikam bruku i żwiru na dojściu",
  savedLocally: "Ustawienia zapisują się tylko na tym telefonie. Zmiana działa od razu na liście, mapie i kartach miejsc.",
  language: "Język",
  // zgłoszenie
  reportIntro: "Uzupełnij to, co wiesz — wystarczy jedno pole. Zgłoszenie pojawi się na karcie jako niezweryfikowane.",
  entrance: "Wejście",
  entranceOptions: [
    ["level", "bez stopni"],
    ["ramp", "podjazd"],
    ["lift", "platforma / winda"],
    ["steps", "stopnie"],
  ] as [string, string][],
  stepCount: "Liczba stopni",
  stepHeight: "Najwyższy próg (cm)",
  doorWidth: "Szerokość drzwi (cm)",
  toilet: "Toaleta dostępna dla wózka",
  changing: "Przewijak",
  elevator: "Winda na inne piętra",
  yesThere: "jest",
  noThere: "nie ma",
  surface: "Nawierzchnia dojścia",
  surfaceOptions: [
    ["smooth", "gładka"],
    ["paving", "kostka"],
    ["cobblestone", "bruk"],
    ["gravel", "żwir"],
  ] as [string, string][],
  comments: "Uwagi (opcjonalnie)",
  commentsLabel: "Uwagi",
  sending: "Wysyłanie…",
  send: "Wyślij zgłoszenie",
  // info
  infoIntro:
    "Nie mówimy „dostępne / niedostępne”. Pokazujemy konkretne bariery i udogodnienia, a przy każdej informacji — skąd pochodzi, z kiedy jest i na ile jest pewna.",
  sources: "Źródła",
  license: "Licencja",
  updates: "Aktualizacja",
  trustLevels: "Poziomy wiarygodności",
  trustConfirmed: "Co najmniej dwa niezależne źródła podają zgodną informację.",
  trustUnverified: "Informacja tylko ze zgłoszeń użytkowników.",
  trustStale: "Najnowsza informacja ma ponad 2 lata.",
  trustConflict: "Źródła się różnią — pokazujemy wszystkie wersje i nie wybieramy za Ciebie.",
  trustSample: "Dane przykładowe przygotowane do demonstracji.",
  privacy: "Prywatność",
  privacyBody:
    "Nie pytamy o niepełnosprawność ani dane osobowe. Profil potrzeb i lokalizacja zostają na telefonie. Zgłoszenia są anonimowe.",
  demo: "Tryb demonstracyjny",
  simulateOutage: "Symuluj awarię OpenStreetMap",
  simulateHint: "Pokazuje, co widzi użytkownik, gdy źródło danych nie odpowiada.",
  server: (u: string) => `Serwer: ${u}`,
  outcome: { ok: "spełnione", barrier: "bariera", unknown: "brak danych", conflict: "sprzeczne dane" },
  /** Opisy źródeł — w polskiej wersji bierzemy je z rejestru SOURCES. */
  sourceDescriptions: {} as Record<string, string>,
};

export type Strings = typeof pl;

const en: Strings = {
  tabSearch: "Search",
  tabMap: "Map",
  tabNeeds: "Needs",
  tabInfo: "Info",
  needsTitle: "Your needs",
  infoTitle: "Sources & method",
  reportTitle: "Report a correction",
  back: "Back",
  brand: "Barrier-free",
  cityLabel: (c) => `City: ${c}. Change city`,
  pickCity: "Choose a city",
  heroTitle: "Where are you going?",
  heroBody: "We check barriers and facilities for your needs — with the source and date of every detail.",
  howYouMove: "How do you get around?",
  searchLabel: "Place name or address",
  searchPlaceholder: "Museum, café, street…",
  clear: "Clear",
  search: "Search",
  all: "All",
  nearMe: "Near me",
  onlyMatching: "Only places that meet my needs",
  loading: "Loading…",
  places: (n) => `${n} ${n === 1 ? "place" : "places"}`,
  nearest: " · nearest first",
  offlineTitle: "You're offline — saved copy",
  offlineBody: (d) => `Results from ${d}. They may be out of date.`,
  sourcesDownTitle: "Some sources are unavailable",
  sourcesDownBody: (names) => `No data from: ${names}. Missing information does not mean there are no barriers.`,
  noServer: "No connection to the server and no saved copy. Try again when you're online.",
  noLocation: "Without location permission we'll sort results by name. You can type an address.",
  openDetails: "Opens details and sources",
  generalOnlyNote: "Based on a general rating, without detailed measurements.",
  tagSample: "Sample data",
  tagUnverified: "Unverified",
  tagStale: "May be out of date",
  tagStaleOne: "May be out of date",
  tagConfirmed: "Confirmed by several sources",
  tagConflict: "Conflicting data",
  mapLabel: "Map of places. The same information is available in the list.",
  mapHint: (n) => `${n} places from your search. Tap a marker to see details.`,
  mapDetails: "Details and sources",
  mapAttribution: "Place data: © OpenStreetMap contributors",
  loadFailed: "Couldn't load this place. Check your connection.",
  verdictA11y: (title, body) => `Rating: ${title}. ${body}`,
  offlineCopyTitle: "You're offline — saved copy",
  offlineCopyBody: (d) => `As of ${d}.`,
  sampleTitle: "Sample data",
  sampleBody: "This entry was prepared for the demo — it does not describe a real venue.",
  generalTitle: "General rating",
  generalBody: "The source says “accessible”, but without detailed measurements of the entrance and doors.",
  unverifiedTitle: "Unverified information",
  unverifiedBody: "Some information comes only from user reports.",
  staleTitle: "May be out of date",
  staleBody: "Some information is more than 2 years old.",
  yourRequirements: "Your requirements",
  changeRequirements: "Change your requirements",
  barriersTitle: "Barriers and facilities",
  barriersHint: "Tap to see the source, date and reliability of each detail.",
  noInfo: "no information",
  noInfoA11y: (label) => `${label}: no information`,
  dateUnknown: "date unknown",
  seeRecord: "See the record at the source →",
  stillTrue: "Have you been there? Is this still accurate?",
  whichTrue: "Have you been there? Which version is correct?",
  yesCurrent: "Yes, still accurate",
  noReport: "No, report a change",
  thanksConfirm: "Thank you — confirmation saved.",
  confirmFailed: "Couldn't save. Please try again.",
  confirmNote: "Confirmed on site",
  transitTitle: "Getting there by public transport",
  onMap: "On the map",
  ownerTitle: "Do you run this place?",
  ownerBody: "Describe its accessibility — your declaration will appear here with a date, and you can embed the card on your website.",
  ownerButton: "Fill in an accessibility declaration",
  osmTitle: "OSM data freshness",
  osmBody: "OpenStreetMap data is imported daily. You can check this place now.",
  osmChecking: "Checking…",
  osmCheck: "Check OpenStreetMap now",
  osmChanged: "OSM has changes since the last import",
  osmSame: "OSM data hasn't changed since the import",
  osmLastEdit: (d) => `Last edit of this object in OSM: ${d}.`,
  osmFailTitle: "Couldn't connect to OpenStreetMap",
  osmFailBody: (d) => `Showing the copy from ${d}. Don't treat it as confirmation of the current state.`,
  lastImport: "the last import",
  navigate: "Directions",
  reportChange: "Report change",
  noStops: "No stops within 600 m in the transit data.",
  stopsHint: "Nearest stops and how boarding works there. Straight-line distance.",
  mode: { bus: "bus", tram: "tram", bus_tram: "bus and tram" },
  approx: (m) => `approx. ${m} m`,
  rest: "Rest",
  shelter: (n) => `shelter (${n})`,
  benches: (n) => `benches (${n})`,
  noRest: "no shelter or benches",
  needsIntro: "Choose how you get around, or set your own requirements. We never ask about disability — your needs are enough.",
  detailedRequirements: "Detailed requirements",
  maxStep: "Highest threshold I can manage (cm)",
  maxStepHint: "For example 2 for a manual wheelchair",
  minDoor: "Passage width I need (cm)",
  minDoorHint: "For example 80",
  needToilet: "I need a wheelchair-accessible toilet",
  needChanging: "I need a baby changing table",
  avoidCobbles: "I avoid cobbles and gravel on the way",
  savedLocally: "Settings are stored only on this phone. Changes apply immediately to the list, map and place cards.",
  language: "Language",
  reportIntro: "Fill in what you know — one field is enough. Your report will appear on the card as unverified.",
  entrance: "Entrance",
  entranceOptions: [
    ["level", "step-free"],
    ["ramp", "ramp"],
    ["lift", "lift / elevator"],
    ["steps", "steps"],
  ],
  stepCount: "Number of steps",
  stepHeight: "Highest threshold (cm)",
  doorWidth: "Door width (cm)",
  toilet: "Wheelchair-accessible toilet",
  changing: "Baby changing table",
  elevator: "Elevator to other floors",
  yesThere: "yes",
  noThere: "no",
  surface: "Approach surface",
  surfaceOptions: [
    ["smooth", "smooth"],
    ["paving", "paving"],
    ["cobblestone", "cobbles"],
    ["gravel", "gravel"],
  ],
  comments: "Comments (optional)",
  commentsLabel: "Comments",
  sending: "Sending…",
  send: "Send report",
  infoIntro:
    "We don't just say “accessible / not accessible”. We show specific barriers and facilities, and for each detail — where it comes from, how recent it is and how reliable.",
  sources: "Sources",
  license: "Licence",
  updates: "Updates",
  trustLevels: "Reliability levels",
  trustConfirmed: "At least two independent sources agree.",
  trustUnverified: "Information only from user reports.",
  trustStale: "The newest information is more than 2 years old.",
  trustConflict: "Sources disagree — we show every version and don't choose for you.",
  trustSample: "Sample data prepared for the demo.",
  privacy: "Privacy",
  privacyBody:
    "We never ask about disability or personal data. Your needs profile and location stay on your phone. Reports are anonymous.",
  demo: "Demo mode",
  simulateOutage: "Simulate an OpenStreetMap outage",
  simulateHint: "Shows what users see when a data source doesn't respond.",
  server: (u) => `Server: ${u}`,
  outcome: { ok: "met", barrier: "barrier", unknown: "no data", conflict: "conflicting data" },
  sourceDescriptions: {
    osm: "Community mapping data. The date shown is the last check (check_date) or the last edit of the object.",
    krakow_open_data:
      "Public toilets (accessibility, access type, changing table), disabled parking inventory and public transport stops (platforms, shelters, benches).",
    owner_declarations:
      "Information provided by the venue manager (hotel, museum, event organiser) via a form or an accessibility.json file on their website.",
    owner_pending:
      "A declaration sent by someone representing the venue. Until verified it is treated as unverified information.",
    user_reports:
      "Observations from visitors. Shown as unverified until confirmed by another user, the owner or a moderator.",
  },
};

const STRINGS: Record<Locale, Strings> = { pl, en };

/** Teksty interfejsu + etykiety danych + komunikaty oceny w języku użytkownika. */
export function useT() {
  const { locale } = useProfile();
  return {
    locale,
    s: STRINGS[locale],
    L: LABELS[locale],
    V: VERDICT_TEXTS[locale],
    M: MESSAGES[locale],
  };
}
